// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mehopswybmfvvtvqbpbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1laG9wc3d5Ym1mdnZ0dnFicGJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxODE2NDIsImV4cCI6MjA2ODc1NzY0Mn0.dKXIurXFcSTvJBejO_qyFGbk4QddTPLJ_34NT1W-1J0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});